server:
  port: 9999


spring:
  data:
    redis:
      # ip
      host: 127.0.0.1
      # ???
      port: 6379
      username: ~
      password: ~
      # ?????
      database: 1



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.note.redis
  configuration:
    # ???????????????????????? A_COLUMN ????? Java ??? aColumn?
    map-underscore-to-camel-case: true